### PR TITLE
share image

### PR DESCRIPTION
**Pull request by erwinkaaa**
function share image to other apps

### CODE REVIEW

**Comment by rahulsain3000** [comment]
hey @erwinkaaa can you also enclose the screenshot of the app.

**Comment by erwinkaaa** [comment]
[in App](https://imgur.com/a/merO7wK) -> [share to other App](https://imgur.com/a/tcAvYl6)

**Comment by rahulsain3000** [comment]
@erwinkaaa thanks for resolving the issue. could you tell me what changes you made in the app and which line convert the meme in .png format?

I am new to development

**Comment by erwinkaaa** [comment]
@rahulsain3000 you're welcome. To implement sharing image, i made a function download, writing bitmap that we get from Glide then we save to cache. Then we can share image with intent action send by using the existing file in cache. The PNG format actually hardcoded, is in line 97.

**Comment by erwinkaaa** [comment]
Hey @rahulsain3000 can you add label hacktoberfest-accepted to this PR please?

**Pull request merged**
